### ISSUE TITLE
Bug - Line breaking issues in Safari

### ISSUE THREAD

**Issue by oliviathevampire** [mineblock11/fabric-community-wiki#27]
### What happened?

Some code lines does not break when that are too long in Safari.

### What browsers are you seeing the problem on?

Safari

### Anything else?

![91E92A83-90E5-4171-A5F3-32B620350F8C](https://user-images.githubusercontent.com/11768384/224183755-26350fb5-b8f4-459d-8115-d1cfd2fcbc33.png)
![0A5FC3E4-64B3-49E7-A714-00C7B81AAED6](https://user-images.githubusercontent.com/11768384/224183774-5d1015d4-9ab4-4b1f-b0f0-e87c1e9fb436.png)

**Comment by mineblock11** [comment]
Doesn't matter, moving to docus
