### ISSUE TITLE
Inconsistency - Navigation description on the items page

### ISSUE THREAD

**Issue by tristankechlo** [mineblock11/fabric-community-wiki#31]
### What is the inconsistency?

The description of the navigation links on the page `/items/` is not their actual description that is used on the corresponding subpages.  
  
**Example:**  
on `/items/` for `Edible Items` the description says  
> This page will guide you through the setup process of your first project using Minecraft Development and IntelliJ IDEA.  
  
but on `/items/food/` the description is  
> Learn how to add a FoodComponent to an item to make it edible, and configure it.
  
<br/><br/>
The same applies for the other navigation links on the `/items/` page

### Anything else?

![Screenshot 2023-03-12 144205](https://user-images.githubusercontent.com/66692834/224548762-947df46c-8e08-4bb6-b296-1d1f3ff9599a.png)

**Comment by mineblock11** [comment]
No clue why this has happened, potentially a git merge error
