### ISSUE TITLE
Bug - "Copy" button location in code blocks

### ISSUE THREAD

**Issue by JR1811** [mineblock11/fabric-community-wiki#37]
### What happened?

When using the horizontal scroll bar in code blocks the "Copy" button moves along with the code content.

It would maybe be better, if the button would stay in place at the top right side of the code content block. This way, when it overlaps with code content, the content still can be accessible when using the horizontal scroll bar.

### What browsers are you seeing the problem on?

Firefox

### Anything else?

For example: 

`/items/item-groups` page's first code block

![button1](https://user-images.githubusercontent.com/36027822/234961466-4a07f967-a909-465c-bece-e19929836697.png)

![button2](https://user-images.githubusercontent.com/36027822/234961485-5c172ade-04df-4f6e-b6bb-3b673e1608a5.png)

**Comment by mineblock11** [comment]
The wiki is being moved to Docus, so this doesn't really matter anymore
