### ISSUE TITLE
Feedback for “Launching the Game”: Misleading Claims about Hotswapping

### ISSUE THREAD

**Issue by Dragon-Seeker** [mineblock11/fabric-community-wiki#55]
- **Mixin Hot Swapping**: Such a claim is very misleading as you can use the sponge-mixin jar as a Java agent to hot-swap code within a mixin class.
- **Lambda Functions**: You can not hot-swap lamdas if the method parameters change in any way. Changing the variables from the outside scope that the lambdas reference will cause the lambda to change its signature, making it a new method entirely.

**Comment by mineblock11** [comment]
Ah, I'll get this fixed asap.
